services:
  - type: web
    name: scholarscapeai
    env: node
    rootDir: server
    buildCommand: npm install --prefix .. && npm run build --prefix ..
    startCommand: PORT=$PORT NODE_ENV=production node ../dist/index.js
    plan: free
